name: Deploy to EdgeOne Pages

on:
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install tiddlywiki

      - name: Build project
        run: |
          mkdir -p node_modules/tiddlywiki/plugins/dyp/
          cp -r plugins/ node_modules/tiddlywiki/plugins/dyp/
          ./node_modules/.bin/tiddlywiki . --output output --build externalimages
          ./node_modules/.bin/tiddlywiki . --output output/library --build library
          ./node_modules/.bin/tiddlywiki . --output output --build gui

      - name: Deploy to EdgeOne Pages
        uses: TencentCloud/tcb-action@v1
        with:
          secretId: ${{ secrets.TCB_SECRET_ID }}
          secretKey: ${{ secrets.TCB_SECRET_KEY }}
          envId: ${{ secrets.TCB_ENV_ID }}
          region: ap-guangzhou
          targetPath: output
