name: Node.js CI

on:
  push:
    branches: [ master ]
  workflowdispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        token: ${{ secrets.GITHUB_PAT }}
    - name: Build Library
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - run: npm install tiddlywiki
    - run: mkdir -p nodemodules/tiddlywiki/plugins/dyp/
    - run: cp -r plugins/ nodemodules/tiddlywiki/plugins/dyp/
    - run: ./nodemodules/.bin/tiddlywiki . --output output/library --build library
    - run: ./nodemodules/.bin/tiddlywiki . --output output --build gui
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        targetbranch: gh-pages
        builddir: output
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
